#Plugin: XPBoost
#Author: Qifi (elving21)
#The variables which start and end with '%' you can either move them around or comepletely remove from the message

database:
  #Type can be: mysql | file
  type: 'file'
  #For MySQL, dont forget to restart server after changing these values
  host: 'localhost'
  port: 3306
  database: 'xpboost'
  user: 'root'
  password: 'root'

settings:
  config_version: 1
  #Supported languages: ENG (English) | NL (Dutch) | ZHS (Simplified Chinese)
  #If you've got a translation to some other language send it to me :)
  language: 'ENG'
  #Enable debug 0 = disabled | 1 = Normal | 2 = All information (Mostly useless for you)
  debug: 0
  #faction support is in development, please use it at your own risk.
  enable_factions: false
  #If you dont want to send metrics (statistics about the plugin)?
  metrics: true
  #Do you want to disable xp bottles? SELECT MODE 1 or 2 or 3
  #Mode 1: Normal behaviour
  #Mode 2: Set dropped XP from xp bottles to 0
  #Mode 3: Disallow players to drop EXP bottles while their boost is active
  xpbottlemode: 1
  #if you want to use only SkillAPI/McMmmo/Heroes/RpgMe etc. experience for example, set this to true, and vanilla xp will be unaffected
  disablevanillaxp: false
  globalboost:
    #Global XP boost
    multiplier: 2.0
    #Enable/disable notification on join when global boost is active
    notification: true
  #Do you want the message about the XP gained to appear
  doublexpmsg: true
  #Actionban msg time delay in ticks, (20 ticks = 1 sec) default 5 sec
  actiondelay: 100
  #Enable/disable motd when global boost is active
  motdon: true
  #Enable/disable actionbar message when boost is active
  actionbarmsg: true
  bossbar:
    #Enable/disable bossbar when boost is active (will work only if BossBar plugin is present)
    bossbarmsg: true
    #Color of the boss bar
    color: BLUE
    #Style of the boss bar
    style: NOTCHED_20
  #Item type material for an xpboost item from /xpb item
  itemmaterial: POTION
  #Sign settings
  sign:
    #line1 is the text that u need to write in order to create sign, other lines will apear automatically
    line1: '&a[XPBoost]'
    line2: '&cOpen'
    #if you dont need other lines, just leave it blank
    line3: ''
    line4: ''
  #Days on which XP boost should be active for everyone! (change to true)
  day:
    monday: false
    teusday: false
    wednesday: false
    thursday: false
    friday: false
    saturday: false
    sunday: false
  #Disabled commands
  disabledcommands:
    #Do you want this feature to be enabled?
    enabled: true
    #List of forbiden commands while XPBoost is active
    list:
    - '/give'
    - '/test'
  #Put it to true if you are using daily global xpboost and ur server does not restart every day
  periodicalDayCheck: false
  #McMMO support
  mcmmo:
    msg:
      enabled: true #do you want a message below to appear?
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Skill: &c%skill%'
  #RPGme support
  rpgme:
    msg:
      enabled: true
      #I disabled message for a STAMINA skill cuz it just spamms rly a lot
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Skill: &c%skill%'
  #Heroes support
  heroes:
    msg:
      enabled: true
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Source: &c%source%'
  #JobsReborn support
  jobs:
    msg:
      enabled: true
      msg: '&aGained &c%newexp% &aXP instead of &c%oldexp%&a. Job: &c%job%'